authorName: default
experimentName: WHU_bohb
trialConcurrency: 1
maxExecDuration: 2d
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: WHU_search_space.json
#choice: true, false
useAnnotation: false
advisor:
  #choice: Hyperband, BOHB
  #(BOHB should be installed through nnictl)
  builtinAdvisorName: BOHB
  classArgs:
    max_budget: 81
    min_budget: 1
    eta: 3
    optimize_mode: maximize
trial:
  command: python3 target_extraction.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu: 1
  useActiveGpu: true

